function F_ps = k2ps(F)
% - transform field from spectral to physical space

F_ps = real( ifft2( F ) );


% OLD VERSION WITH ZERO-PADDING FOR ANTI-ALIASING
% - use zero padding for anti-aliasing, expand matrix from size N^2
%   to size (3N/2)^2
% 
% F_ps = (3/2)^2 *real(ifft2( ...
%         cat(1, ...
%                cat(2,   F(1:N/2,1:N/2),   zeros(N/2,N/2+1),   F(1:N/2,N/2+2:N) ), ...
%                zeros(N/2+1,3*N/2), ...
%                cat(2, F(N/2+2:N,1:N/2), zeros(N/2-1,N/2+1), F(N/2+2:N,N/2+2:N) ) ...
%             ) ...
%         ));
